name: Demo Approval

on:
  push:
    tags:
      - dev

env:
  PROJECT: approval_sample

jobs:

  build:
    name: Deploy to Development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & Deploy
        run: |
          echo "$GITHUB_WORKSPACE"
          echo "Building"
          echo "Deploying"
